### ISSUE TITLE
TypeError: Interval() takes no arguments

### ISSUE THREAD

**Issue by anorprogrammer** [pydantic/FastUI#105]
Operating system: Windows 11
Python version: 3.9.7
FastUI version: 0.3.0

Error:

```console
Traceback (most recent call last):
  File "D:\Learning\FastUI\fastui-demo\main.py", line 5, in <module>
    from fastui import FastUI, AnyComponent, prebuilt_html, components as c
  File "D:\Learning\FastUI\fastui-demo\env\lib\site-packages\fastui\__init__.py", line 5, in <module>
    from .components import AnyComponent
  File "D:\Learning\FastUI\fastui-demo\env\lib\site-packages\fastui\components\__init__.py", line 15, in <module>
    from .display import Details, Display
  File "D:\Learning\FastUI\fastui-demo\env\lib\site-packages\fastui\components\display.py", line 33, in <module>
    class DisplayLookup(DisplayBase, extra='forbid'):
  File "D:\Learning\FastUI\fastui-demo\env\lib\site-packages\fastui\components\display.py", line 40, in DisplayLookup
    table_width_percent: _t.Union[_te.Annotated[int, _at.Interval(ge=0, le=100)], None] = pydantic.Field(
TypeError: Interval() takes no arguments
```

**Comment by samuelcolvin** [comment]
It definitely does, see [here](https://github.com/annotated-types/annotated-types/blob/195e3406a276d3599fb94f6f982f5e91837de4a3/annotated_types/__init__.py#L204).

I don't think this can be an error in FastUI.

**Comment by samuelcolvin** [comment]
Also, this is run in tests and doesn't fail

**Comment by chenwang07** [comment]
I have the some issue
in `types.py`, `annotated_types.Interval(gt=gt,ge=ge,lt=lt,le=le) ` will throw exception, definitely a bug

**Comment by jokasinski** [comment]
This appears to be an instance of https://github.com/python/cpython/issues/89244 which affects using `@dataclass` and `Protocol` together.  It was [fixed](https://docs.python.org/3.9/whatsnew/changelog.html#python-3-9-8-final) in Python 3.9.8, so upgrading your Python version should help.
