### ISSUE TITLE
`ServerLoad` a `ModelForm`

### ISSUE THREAD

**Issue by ckming102** [pydantic/FastUI#143]
Firstly thanks for starting this project. I've been experimenting with it for  2 weeks plus now, and it does feel like it hits a sweet spot for back-end driven for UI's. I'm really enjoying it using so far.

So one thing that I have been trying is dynamically load content through server-load but using a model form to update this content. If I make the model form a page component, the form disappears entirely after submission. And if I encapsulate it within its own server load -- so that I can reload it after submission --  then I get what looks like a FastUI error. 

An MRE
```python
from typing import Annotated

from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from fastui import FastUI, AnyComponent, components as c, prebuilt_html
from fastui.forms import fastui_form
from fastui.events import PageEvent
from pydantic import BaseModel, Field

app = FastAPI()


content: str = "**Some content**"


class AppendForm(BaseModel):
    new_text: str = Field(default="", description="Additional text")


@app.post("/api/append_form", response_model=FastUI, response_model_exclude_none=True)
async def process_form(form: Annotated[AppendForm, fastui_form(AppendForm)]) -> list[AnyComponent]:
    global content
    content = (
        content
        + f"""\\
**{form.new_text}**"""
    )
    return [
        c.FireEvent(event=PageEvent(name="reload-content", push_path="/")),
        c.FireEvent(event=PageEvent(name="load-form")),
    ]


@app.get("/api/content", response_model=FastUI, response_model_exclude_none=True)
def server_content() -> list[AnyComponent]:
    return [c.Markdown(text=content)]


@app.get("/api/form", response_class=FastUI, response_model_exclude_none=True)
def get_form() -> list[AnyComponent]:
    return [
        c.ModelForm(
            model=AppendForm,
            submit_url="/api/append_form",
            method="POST",
            initial={"new_text": ""},
        ),
    ]


@app.get("/api/", response_model=FastUI, response_model_exclude_none=True)
async def index() -> list[AnyComponent]:
    return [
        c.Page(
            components=[
                c.Heading(text="Severload and Form demo", level=2),
                c.ServerLoad(
                    path="/content",
                    components=server_content(),
                    load_trigger=PageEvent(name="reload-content"),
                ),
                c.ServerLoad(
                    path="/form",
                    components=get_form(),
                    load_trigger=PageEvent(name="load-form"),
                ),
            ]
        ),
    ]


@app.get("/{path:path}")
async def html_landing() -> HTMLResponse:
    """Simple HTML page which serves the React app, comes last as it matches all paths."""
    return HTMLResponse(prebuilt_html(title="FastUI Demo"))

``` 
But I am getting behavior like so:

https://github.com/pydantic/FastUI/assets/87660989/7d315903-566a-4db7-9685-cc208d68f2d9

The debug `Traceback` shows a `AGSI` exception:
```term
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/fastapi/routing.py", line 326, in app
    response = actual_response_class(content, **response_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mingsy/Desktop/p_projects/fast-ui/env311/lib/python3.11/site-packages/pydantic/root_model.py", line 59, in __init__
    raise ValueError(
ValueError: "RootModel.__init__" accepts either a single positional argument or arbitrary keyword arguments
```

Not sure if FastUI is meant to be used this way.

Thanks again,

Ming

**Comment by ckming102** [comment]
So I am closing this now because I found the mistake in my code
```
@app.get("/api/form", response_class=FastUI, response_model_exclude_none=True)
def get_form() -> list[AnyComponent]:
    ...
```
`response_class` should be `response_model` instead.
